### ISSUE TITLE
Setup Factory Extraction Support

### ISSUE THREAD

**Issue by xorhex** [CybercentreCanada/assemblyline-service-extract#266]
Possible to add extraction support for Setup Factory installers?  Thanks!

Test Sample: 21321fbdc67896cc8e41cbf2c4c8430ecf5992040491fc477864c5363e3ae3d8

https://medium.com/@FatzQatz/unveiling-the-mustang-panda-operation-attack-on-thai-parliament-member-ac197a1ad8fa

**Comment by xorhex** [comment]
Hey!

All I've been able to find so far is https://github.com/Bioruebe/UniExtract2/releases (have not tried it) but at the same time guessing it only has support for older version of Setup Factory (https://github.com/Bioruebe/UniExtract2/issues/52#issuecomment-297091526)

**Comment by xorhex** [comment]
Have not tried this either, but looks promising: https://github.com/Puyodead1/SFUnpacker

**Comment by gdesmar** [comment]
I'll add [suf001](https://sourceforge.net/projects/innounp/files/other%20stuff/Setup%20Factory%20unpacker/) to the list in case it could become handy. 

Sadly, UniExtract and suf001 does not look to be running well on Wine, and for the moment, we are running all of our tool on Linux.

I looked at SFUnpacker, and it doesn't seem to have an official release. I tried to download the original [Observer](https://github.com/lazyhamster/Observer/) from which most of the code come from, and it's not pre-compiled either. They refer vcpkg and Visual Studio, which are both Windows tools, but vcpkg looks to support Linux? Maybe there is a way to compile it to run on Linux, but I wouldn't hold my breath there. Maybe there's a way to compile it on Windows and run it in Wine, but that would also need a few tests.

I took a quick look at the code, and it's not too large. The overlay of your initial test sample is indeed starting with the [SetupFactory8 signature](https://github.com/Puyodead1/SFUnpacker/blob/main/SFUnpacker/SetupFactory8.cpp#L8), so I'd really love to add support if we find a way to run the code, or someone wants to rewrite it in python...! I may look into that later, but I have no timeline and no guarantee. I see an [`#include <Windows.h>`](https://github.com/Puyodead1/SFUnpacker/blob/main/SFUnpacker/Streams.h#L7) and depending on how it's used, may break easy portability.

**Comment by gdesmar** [comment]
Hello!
I have some good news! I went over SFUnpacker and ported all of the important code to a new library called sfextract ([pypi](https://pypi.org/project/sfextract/), [github](https://github.com/CybercentreCanada/sfextract)). I now added that library as a dependency in Extract, and starting with version 4.5.0.stable42, will extract all files that it can.

The new internal library sfextract support almost everything that SFUnpacker did, but there are still a few things missing (LZMA2 compressed data). It covers everything needed for your test sample to extracts the word document, executable and dll, plus some SetupFactory resource files.

If you want to install sfextract by itself, using `pip install sfextract`, you will also be able to just execute the `sfextract` command from the commandline on your executable, and it will extract the files in a folder next to your file.

If you have more samples that do not get opened correctly with sfextract, you can open a ticket on the sfextract repository. If you have issues for the Extract service, or any other Assemblyline tool, you can also open an issue on our [centralize issue tracker](https://github.com/CybercentreCanada/assemblyline/issues) to get more eyes on it, in case we miss the service repository issues.

**Comment by xorhex** [comment]
This is amazing - thank you!
