### ISSUE TITLE
Unable to extract MSI files

### ISSUE THREAD

**Issue by 0xd0cf11e** [CybercentreCanada/assemblyline-service-extract#28]
The extract service is unable to extract from MSI file where the file type is detected as `document/installer/windows`. Example file in question - https://www.virustotal.com/gui/file/2c0d8fc0740598fa97c5d1b21edb011c8026740b77029d29c20f3275438ebfbd

Locally 7zip is able to extract the files. The problem lies with the conditional check made in the `extract_zip` function - https://github.com/CybercentreCanada/assemblyline-service-extract/blob/master/extract/extract.py#L673

**Comment by cccs-kevin** [comment]
Hey thanks for this @0xd0cf11e, I'll get started on a PR right away!
