### ISSUE TITLE
Bug: Infinite loop in 7zip extraction

### ISSUE THREAD

**Issue by hawken93** [CybercentreCanada/assemblyline-service-extract#61]
Hi,

I believe I have found an infinite loop bug in the extract service. The bug was suspected after 39 minutes of 100% cpu usage, even though the time limit should have been 60 seconds. The version is 4.2.0.stable26, but I haven't seen any changes to this mechanic in master. This is running in kubernetes via the assemblyline helm chart (v4.2) :)

Stack trace shows for extract.py:
- 260 (extract)
- 726 (extract_zip)
- 802 (extract_zip_7zip)
- 434 (_7zip_submit_extracted)
- os.walk

strace:
-  openat /tmp/working_directory/tmp.../extracted_zip = -1 ENOENT (No such file or directory) * repeated indefinitely
  
Reasons:
- while changes_made -> no os.walk -> no clearing of changes_made flag
- The folder seems to be made from the unzip operation, but the unzip operation could fail, apparently without making a folder.

Possible solutions:
- Check if the unzip operation was successful, via return code?
- The loop on line 433 could be structured so as to clear the flag before the os.walk, so that unless os.walk sets it then the loop is exited.
```py
changes_made = True
while changes_made:
  changes_made = False
  for ... in os.walk(path):
    ...
    if this or that:
      changes_made = True
```

Cheers :)

**Comment by cccs-rs** [comment]
Should be resolved in: [v4.2.0.stable27](https://github.com/CybercentreCanada/assemblyline-service-extract/releases/tag/v4.2.0.stable27)
